version: '3.9'

services:
    remix:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: remix-app
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - '5173:5173'
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - remix-net
        command: ['pnpm', 'dev']

    db:
        image: postgres:15
        container_name: remix-db
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - remix-net

volumes:
    pgdata:

networks:
    remix-net:
