name: ec2 setup

on:
    push:
        branches: [master]

jobs:
    deploy:
        # make sure these labels match your runner (check in GitHub UI)
        runs-on: [self-hosted, linux, X64]

        timeout-minutes: 20

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Show runner info
              run: |
                  echo "Runner labels: $RUNNER_OS $RUNNER_ARCH"
                  docker --version
                  docker compose version

            - name: Ensure runner user can use docker
              run: |
                  whoami
                  groups
                  docker ps

            - name: Stop old containers
              working-directory: ./ # <- folder with docker-compose.yml
              run: |
                  docker compose down || true

            - name: Build and start
              working-directory: ./ # <- folder with docker-compose.yml
              run: |
                  docker compose pull || true
                  docker compose up -d --build

            - name: Health check
              run: |
                  docker ps
                  docker compose ls
