name: ec2 deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: self-hosted
        timeout-minutes: 25
        steps:
            - uses: actions/checkout@v4

            - name: Show runner info
              run: |
                  pwd && ls -la
                  docker --version
                  docker compose version

            - name: Ensure .env for compose
              run: |
                  cp "$HOME/actions-runner/.env" ./.env
                  chmod 600 ./.env
                  sed -n '1,50p' .env | sed 's/=.*/=<hidden>/'

            - name: Validate compose
              run: docker compose config

            - name: Stop old containers
              run: docker compose down || true

            - name: Build and start
              run: |
                  docker compose pull || true
                  docker compose up -d --build

            - name: Health check
              run: |
                  docker compose ps
                  docker compose logs --tail=100
