name: Deploy to EC2 Self-Hosted Runner

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Stop old containers
              run: docker-compose down || true

            - name: Build and start new containers
              run: docker-compose up -d --build

            - name: Show running containers
              run: docker ps
